# Generated by Django 6.0.1 on 2026-03-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь может проверять и одобрять видео.', verbose_name='Модератор'),
        ),
    ]
