# Generated by Django 6.0.1 on 2026-01-30 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('preview', models.ImageField(blank=True, default='previews/default.png', null=True, upload_to='previews/')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_videos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие дизлайк')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, поставившие лайк')),
                ('views', models.ManyToManyField(blank=True, related_name='viewed_videos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, просмотревшие видео')),
            ],
        ),
    ]
