# Generated by Django 6.0.1 on 2026-03-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0002_category_videoitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
