# Generated by Django 6.0.1 on 2026-03-03 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0003_videoitem_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='videoitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения категорий'),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено модератором'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videohost.videoitem', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videohost.videoitem', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videohost.category'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='view',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videohost.videoitem', verbose_name='Видео'),
        ),
    ]
