# Generated by Django 6.0.1 on 2026-03-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0004_alter_category_options_alter_videoitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='videoitem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='videohost.tag'),
        ),
    ]
