# Generated by Django 6.0.1 on 2026-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videohost', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='videoitem',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
